import LegalBanner from '@/components/LegalBanner';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | Tacit',
  description: 'Terms governing the use of the Tacit website and assessment tools.',
};

export default function TermsPage() {
  return (
    <div style={{ maxWidth: '840px', margin: '40px auto', display: 'grid', gap: '32px' }}>
      <LegalBanner />

      <div>
        <span className="eyebrow">Legal Notice</span>
        <h1 style={{ marginTop: '8px', marginBottom: '12px' }}>Terms of Service</h1>
        <p className="mono" style={{ fontSize: '13px', color: 'var(--ink-2)' }}>
          Last revised: October 2026 · Inception2c LLC d/b/a Tacit
        </p>
      </div>

      <div style={{ display: 'grid', gap: '24px', lineHeight: '1.7', color: 'var(--ink-2)' }}>
        <section style={{ borderTop: 'none', paddingBlock: 0 }}>
          <h2 style={{ fontSize: '20px', color: 'var(--ink)', marginBottom: '8px' }}>1. Acceptance of Terms</h2>
          <p>
            By accessing or using the website at tacit.exchange (the &quot;Site&quot;) or any online diagnostic calculators, rights evaluation forms, or request portals operated by Inception2c LLC d/b/a Tacit (&quot;Tacit&quot;), you agree to comply with and be bound by these Terms of Service.
          </p>
        </section>

        <section style={{ borderTop: 'none', paddingBlock: 0 }}>
          <h2 style={{ fontSize: '20px', color: 'var(--ink)', marginBottom: '8px' }}>2. Informational and Estimator Disclaimer</h2>
          <p>
            All figures, calculations, and valuation estimates generated by the on-site valuation calculator or rights checklists are provided strictly for illustrative, non-binding informational purposes. The output of any online tool does not constitute a formal appraisal, commercial offer, guarantee of purchase, or legal advice. Final licensing agreements are subject to bilateral contract execution, rights review, and verified buyer acceptance.
          </p>
        </section>

        <section style={{ borderTop: 'none', paddingBlock: 0 }}>
          <h2 style={{ fontSize: '20px', color: 'var(--ink)', marginBottom: '8px' }}>3. Proprietary Rights</h2>
          <p>
            All trademarks, logos, design marks (including the Tacit redaction motif), software code, editorial text, and calculation algorithms on this Site are the intellectual property of Inception2c LLC. Unauthorized reproduction, automated scraping, or frame inclusion without prior written consent is strictly prohibited.
          </p>
        </section>

        <section style={{ borderTop: 'none', paddingBlock: 0 }}>
          <h2 style={{ fontSize: '20px', color: 'var(--ink)', marginBottom: '8px' }}>4. Commercial Agreements Control</h2>
          <p>
            The formal relationship between Tacit and any commercial data seller or buyer is governed solely by individually executed Master Brokerage Agreements, Restrictive Training Licences, and Escrow Instructions. In the event of any conflict between this Site content and an executed commercial agreement, the executed agreement shall govern.
          </p>
        </section>

        <section style={{ borderTop: 'none', paddingBlock: 0 }}>
          <h2 style={{ fontSize: '20px', color: 'var(--ink)', marginBottom: '8px' }}>5. Governing Law and Forum</h2>
          <p>
            These Terms of Service are governed by the laws of the State of Delaware, United States, without regard to choice of law principles. Any dispute arising out of your access to this Site shall be resolved exclusively in the state or federal courts situated in Delaware.
          </p>
        </section>
      </div>
    </div>
  );
}
